apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: {{NAMESPACE}}
  labels:
    app: eureka
spec:
  ports:
    - port: 8761
      name: eureka
  clusterIP: None
  selector:
    app: eureka-cluster